env: wildfire

env_args:
  map_name: "circular"
  episode_limit: 320
  desired_comm_dist: 50
  r_collision_avoidance: 5
  n_agents: 3
  kick_start_timesteps: 12
  t_env_update: 4
  x_len: 100
  y_len: 100
  # fire_x_start: 48
  # fire_y_start: 48
  # fire_x_end: 52
  # fire_y_end: 52
  flame_min: 15
  flame_max: 20
  dmax: 2.5
  K: 0.05
  seed: null
  d_sight: 10
  est_fire_noise: 5
  rho: 0.25
  rho_n: 0.15

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 250000
